/** Refresh the web catalog only from validated, frozen maze artifacts. */
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { RaceCourse } from '../packages/race/src/index.ts';

const root = resolve(import.meta.dirname, '..');
const slugs = [
  'flow-delta',
  'hairpin-terraces',
  'skipping-stones',
  'twin-canyons',
  'cliff-ribbon',
  'bankshot-basin',
  'switchyard',
  'sky-weave',
  'needle-garden',
  'redline-relay',
];
const catalog = [];
for (const slug of slugs) {
  let course: RaceCourse;
  try {
    course = JSON.parse(await readFile(resolve(root, 'fixtures/race', slug, 'course.json'), 'utf8'));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') continue;
    throw error;
  }
  const published = JSON.parse(
    await readFile(resolve(root, 'apps/web/public/race', slug, 'course.json'), 'utf8'),
  );
  if (JSON.stringify(course) !== JSON.stringify(published)) throw new Error(`${slug}: public artifact drift`);
  catalog.push({
    slug,
    courseId: course.courseId,
    title: course.title,
    description: course.description,
    islands: course.stage.islands.length,
    previewUrl: `/race/${slug}/texture.png`,
    courseUrl: `/race/${slug}/course.json`,
  });
}
await writeFile(
  resolve(root, 'apps/web/src/race/maze-catalog.ts'),
  '/** Generated by scripts/race-maze-catalog.ts. */\nexport const MAZE_COURSES = ' +
    JSON.stringify(catalog, null, 2) +
    ' as const;\n',
);
console.log(`${catalog.length} maze entries updated`);
